<a href="https://colab.research.google.com/github/hpnightowl/owlsbooks/blob/master/autogulon.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [52]:
pip install datacleaner

Requirement already satisfied: datacleaner in /usr/local/lib/python3.6/dist-packages (0.1.5)
Requirement already satisfied: pandas in /usr/local/lib/python3.6/dist-packages (from datacleaner) (0.25.3)
Requirement already satisfied: update-checker in /usr/local/lib/python3.6/dist-packages (from datacleaner) (0.18.0)
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.6/dist-packages (from datacleaner) (0.22.2.post1)
Requirement already satisfied: numpy>=1.13.3 in /usr/local/lib/python3.6/dist-packages (from pandas->datacleaner) (1.18.5)
Requirement already satisfied: pytz>=2017.2 in /usr/local/lib/python3.6/dist-packages (from pandas->datacleaner) (2018.9)
Requirement already satisfied: python-dateutil>=2.6.1 in /usr/local/lib/python3.6/dist-packages (from pandas->datacleaner) (2.8.1)
Requirement already satisfied: requests>=2.3.0 in /usr/local/lib/python3.6/dist-packages (from update-checker->datacleaner) (2.23.0)
Requirement already satisfied: scipy>=0.17.0 in /usr/local/lib/python3.6/dist-packages (from scikit-learn->datacleaner) (1.4.1)
Requirement already satisfied: joblib>=0.11 in /usr/local/lib/python3.6/dist-packages (from scikit-learn->datacleaner) (0.16.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.6/dist-packages (from python-dateutil>=2.6.1->pandas->datacleaner) (1.15.0)
Requirement already satisfied: chardet<4,>=3.0.2 in /usr/local/lib/python3.6/dist-packages (from requests>=2.3.0->update-checker->datacleaner) (3.0.4)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.6/dist-packages (from requests>=2.3.0->update-checker->datacleaner) (2020.6.20)
Requirement already satisfied: idna<3,>=2.5 in /usr/local/lib/python3.6/dist-packages (from requests>=2.3.0->update-checker->datacleaner) (2.10)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /usr/local/lib/python3.6/dist-packages (from requests>=2.3.0->update-checker->datacleaner) (1.24.3)

In [53]:
import pandas as pd
from sklearn.model_selection import train_test_split
sd  = pd.read_csv("https://raw.githubusercontent.com/dphi-official/Datasets/master/startupdata/training_set_label.csv" )
td = pd.read_csv('https://raw.githubusercontent.com/dphi-official/Datasets/master/startupdata/testing_set_label.csv')
sd = sd.drop(columns=['Unnamed: 0','Unnamed: 6','state_code.1','closed_at','object_id','is_CA' ,'is_NY' ,'has_VC' ,'has_roundB' ,'has_roundC' ,'has_roundD' ,'has_roundA' ,'is_ecommerce' ,'is_biotech' ,'is_gamesvideo', 'is_enterprise' ,'is_mobile' ,'is_web', 'is_software', 'is_otherstate', 'has_angel' ,'is_MA', 'is_othercategory' ,'state_code'],axis =1)
td = td.drop(columns=['Unnamed: 0','Unnamed: 6','state_code.1','closed_at','object_id','is_CA' ,'is_NY' ,'has_VC' ,'has_roundB' ,'has_roundC' ,'has_roundD' ,'has_roundA' ,'is_ecommerce' ,'is_biotech' ,'is_gamesvideo', 'is_enterprise' ,'is_mobile' ,'is_web', 'is_software', 'is_otherstate', 'has_angel','is_MA', 'is_othercategory' ,'state_code'],axis =1)

In [54]:
sd

      latitude   longitude zip_code  ... avg_participants is_top500    status
0    42.358880  -71.056820    92101  ...           1.0000         0  acquired
1    37.238916 -121.973718    95032  ...           4.7500         1  acquired
2    32.901049 -117.192656    92121  ...           4.0000         1  acquired
3    37.320309 -122.050040    95014  ...           3.3333         1  acquired
4    37.779281 -122.419236    94105  ...           1.0000         1    closed
..         ...         ...      ...  ...              ...       ...       ...
918  37.740594 -122.376471    94107  ...           6.0000         1  acquired
919  42.504817  -71.195611     1803  ...           2.6667         1    closed
920  37.408261 -122.015920    94089  ...           8.0000         1    closed
921  37.556732 -122.288378    94404  ...           1.0000         1  acquired
922  37.386778 -121.966277    95054  ...           3.0000         1  acquired

[923 rows x 24 columns]

In [55]:
td

      latitude   longitude zip_code  ... is_consulting avg_participants is_top500
0    41.321520  -72.929423     6511  ...             0           1.3333         1
1    37.452084 -122.112879    94303  ...             0           6.0000         1
2    40.296222  -74.050972     7724  ...             0           2.0000         0
3    37.789268 -122.395184    94105  ...             0           1.0000         0
4    33.133240 -117.275027    92011  ...             0           5.5000         1
..         ...         ...      ...  ...           ...              ...       ...
226  45.520247 -122.674195    97214  ...             0           4.0000         0
227  37.440682 -122.123103    94303  ...             0           1.5000         1
228  37.496904 -122.333057    94107  ...             0           4.0000         1
229  40.728425  -73.999882    10012  ...             0          15.0000         1
230  40.756799  -73.976348    10001  ...             0           2.6667         1

[231 rows x 23 columns]

In [56]:
X = sd.drop('status',axis=1)
sd['age_first_milestone_year'].fillna(sd['age_first_milestone_year'].mode()[0], inplace=True)
sd['age_last_milestone_year'].fillna(sd['age_last_milestone_year'].mode()[0], inplace=True)
td['age_first_milestone_year'].fillna(td['age_first_milestone_year'].mode()[0], inplace=True)
td['age_last_milestone_year'].fillna(td['age_last_milestone_year'].mode()[0], inplace=True)
# Import label encoder 
from sklearn import preprocessing
# label_encoder object knows how to understand word labels. 
le = preprocessing.LabelEncoder()
# Encode labels in column 'Country'. 
X['id'] = le.fit_transform(X['id'])
X['city'] = le.fit_transform(X['city'])
X['zip_code'] = le.fit_transform(X['zip_code'])
X['name'] = le.fit_transform(X['name'])
X['category_code'] = le.fit_transform(X['category_code'])
X['first_funding_at'] = le.fit_transform(X['first_funding_at'])
X['last_funding_at'] = le.fit_transform(X['last_funding_at'])
X['founded_at'] = le.fit_transform(X['founded_at'])
td['id'] = le.fit_transform(td['id'])
td['city'] = le.fit_transform(td['city'])
td['name'] = le.fit_transform(td['name'])
td['zip_code'] = le.fit_transform(td['zip_code'])
td['category_code'] = le.fit_transform(td['category_code'])
td['first_funding_at'] = le.fit_transform(td['first_funding_at'])
td['last_funding_at'] = le.fit_transform(td['last_funding_at'])
td['founded_at'] = le.fit_transform(td['founded_at'])

y = sd[['status']]

In [57]:
newdata = pd.concat([X, y], axis=1, sort=False)
new_train = pd.DataFrame(newdata) 
new_test = pd.DataFrame(td) 
# saving the dataframe 
new_train.to_csv('hptrain.csv')
new_test.to_csv('hptest.csv')
new_train

      latitude   longitude  zip_code  ...  avg_participants  is_top500    status
0    42.358880  -71.056820       250  ...            1.0000          0  acquired
1    37.238916 -121.973718       336  ...            4.7500          1  acquired
2    32.901049 -117.192656       251  ...            4.0000          1  acquired
3    37.320309 -122.050040       333  ...            3.3333          1  acquired
4    37.779281 -122.419236       295  ...            1.0000          1    closed
..         ...         ...       ...  ...               ...        ...       ...
918  37.740594 -122.376471       296  ...            6.0000          1  acquired
919  42.504817  -71.195611        45  ...            2.6667          1    closed
920  37.408261 -122.015920       290  ...            8.0000          1    closed
921  37.556732 -122.288378       314  ...            1.0000          1  acquired
922  37.386778 -121.966277       343  ...            3.0000          1  acquired

[923 rows x 24 columns]

In [58]:
new_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 923 entries, 0 to 922
Data columns (total 24 columns):
latitude                    923 non-null float64
longitude                   923 non-null float64
zip_code                    923 non-null int64
id                          923 non-null int64
city                        923 non-null int64
name                        923 non-null int64
founded_at                  923 non-null int64
first_funding_at            923 non-null int64
last_funding_at             923 non-null int64
age_first_funding_year      923 non-null float64
age_last_funding_year       923 non-null float64
age_first_milestone_year    771 non-null float64
age_last_milestone_year     771 non-null float64
relationships               923 non-null int64
funding_rounds              923 non-null int64
funding_total_usd           923 non-null int64
milestones                  923 non-null int64
is_TX                       923 non-null int64
category_code               923 non-null int64
is_advertising              923 non-null int64
is_consulting               923 non-null int64
avg_participants            923 non-null float64
is_top500                   923 non-null int64
status                      923 non-null object
dtypes: float64(7), int64(16), object(1)
memory usage: 173.2+ KB

In [59]:
# https://autogluon.mxnet.io/
!pip install --upgrade mxnet
!pip install autogluon

Requirement already up-to-date: mxnet in /usr/local/lib/python3.6/dist-packages (1.7.0.post1)
Requirement already satisfied, skipping upgrade: graphviz<0.9.0,>=0.8.1 in /usr/local/lib/python3.6/dist-packages (from mxnet) (0.8.4)
Requirement already satisfied, skipping upgrade: requests<3,>=2.20.0 in /usr/local/lib/python3.6/dist-packages (from mxnet) (2.23.0)
Requirement already satisfied, skipping upgrade: numpy<2.0.0,>1.16.0 in /usr/local/lib/python3.6/dist-packages (from mxnet) (1.18.5)
Requirement already satisfied, skipping upgrade: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /usr/local/lib/python3.6/dist-packages (from requests<3,>=2.20.0->mxnet) (1.24.3)
Requirement already satisfied, skipping upgrade: certifi>=2017.4.17 in /usr/local/lib/python3.6/dist-packages (from requests<3,>=2.20.0->mxnet) (2020.6.20)
Requirement already satisfied, skipping upgrade: idna<3,>=2.5 in /usr/local/lib/python3.6/dist-packages (from requests<3,>=2.20.0->mxnet) (2.10)
Requirement already satisfied, skipping upgrade: chardet<4,>=3.0.2 in /usr/local/lib/python3.6/dist-packages (from requests<3,>=2.20.0->mxnet) (3.0.4)
Requirement already satisfied: autogluon in /usr/local/lib/python3.6/dist-packages (0.0.13)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.6/dist-packages (from autogluon) (3.2.2)
Requirement already satisfied: gluoncv<1.0,>=0.5.0 in /usr/local/lib/python3.6/dist-packages (from autogluon) (0.8.0)
Requirement already satisfied: dask>=2.6.0 in /usr/local/lib/python3.6/dist-packages (from autogluon) (2.12.0)
Requirement already satisfied: pandas<1.0,>=0.24.0 in /usr/local/lib/python3.6/dist-packages (from autogluon) (0.25.3)
Requirement already satisfied: pyarrow<=1.0.0 in /usr/local/lib/python3.6/dist-packages (from autogluon) (0.14.1)
Requirement already satisfied: psutil<=5.7.0,>=5.0.0 in /usr/local/lib/python3.6/dist-packages (from autogluon) (5.4.8)
Requirement already satisfied: networkx<3.0,>=2.3 in /usr/local/lib/python3.6/dist-packages (from autogluon) (2.5)
Requirement already satisfied: Pillow<=6.2.1 in /usr/local/lib/python3.6/dist-packages (from autogluon) (6.2.1)
Requirement already satisfied: boto3 in /usr/local/lib/python3.6/dist-packages (from autogluon) (1.14.48)
Requirement already satisfied: cython in /usr/local/lib/python3.6/dist-packages (from autogluon) (0.29.21)
Requirement already satisfied: paramiko>=2.4 in /usr/local/lib/python3.6/dist-packages (from autogluon) (2.7.2)
Requirement already satisfied: scipy>=1.3.3 in /usr/local/lib/python3.6/dist-packages (from autogluon) (1.4.1)
Requirement already satisfied: openml in /usr/local/lib/python3.6/dist-packages (from autogluon) (0.10.2)
Requirement already satisfied: fastparquet==0.4.1 in /usr/local/lib/python3.6/dist-packages (from autogluon) (0.4.1)
Requirement already satisfied: tornado>=5.0.1 in /usr/local/lib/python3.6/dist-packages (from autogluon) (5.1.1)
Requirement already satisfied: graphviz<0.9.0,>=0.8.1 in /usr/local/lib/python3.6/dist-packages (from autogluon) (0.8.4)
Requirement already satisfied: pytest in /usr/local/lib/python3.6/dist-packages (from autogluon) (3.6.4)
Requirement already satisfied: ConfigSpace<=0.4.10 in /usr/local/lib/python3.6/dist-packages (from autogluon) (0.4.10)
Requirement already satisfied: distributed>=2.6.0 in /usr/local/lib/python3.6/dist-packages (from autogluon) (2.25.0)
Requirement already satisfied: autogluon-contrib-nlp in /usr/local/lib/python3.6/dist-packages (from autogluon) (0.0.1b20200815)
Requirement already satisfied: scikit-optimize in /usr/local/lib/python3.6/dist-packages (from autogluon) (0.8.1)
Requirement already satisfied: scikit-learn<0.23,>=0.22.0 in /usr/local/lib/python3.6/dist-packages (from autogluon) (0.22.2.post1)
Requirement already satisfied: catboost<0.24 in /usr/local/lib/python3.6/dist-packages (from autogluon) (0.23.2)
Requirement already satisfied: lightgbm<3.0,>=2.3.0 in /usr/local/lib/python3.6/dist-packages (from autogluon) (2.3.1)
Requirement already satisfied: numpy>=1.16.0 in /usr/local/lib/python3.6/dist-packages (from autogluon) (1.18.5)
Requirement already satisfied: tqdm>=4.38.0 in /usr/local/lib/python3.6/dist-packages (from autogluon) (4.41.1)
Requirement already satisfied: requests in /usr/local/lib/python3.6/dist-packages (from autogluon) (2.23.0)
Requirement already satisfied: cryptography>=2.8 in /usr/local/lib/python3.6/dist-packages (from autogluon) (3.1)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1 in /usr/local/lib/python3.6/dist-packages (from matplotlib->autogluon) (2.4.7)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.6/dist-packages (from matplotlib->autogluon) (0.10.0)
Requirement already satisfied: python-dateutil>=2.1 in /usr/local/lib/python3.6/dist-packages (from matplotlib->autogluon) (2.8.1)
Requirement already satisfied: kiwisolver>=1.0.1 in /usr/local/lib/python3.6/dist-packages (from matplotlib->autogluon) (1.2.0)
Requirement already satisfied: portalocker in /usr/local/lib/python3.6/dist-packages (from gluoncv<1.0,>=0.5.0->autogluon) (2.0.0)
Requirement already satisfied: pytz>=2017.2 in /usr/local/lib/python3.6/dist-packages (from pandas<1.0,>=0.24.0->autogluon) (2018.9)
Requirement already satisfied: six>=1.0.0 in /usr/local/lib/python3.6/dist-packages (from pyarrow<=1.0.0->autogluon) (1.15.0)
Requirement already satisfied: decorator>=4.3.0 in /usr/local/lib/python3.6/dist-packages (from networkx<3.0,>=2.3->autogluon) (4.4.2)
Requirement already satisfied: botocore<1.18.0,>=1.17.48 in /usr/local/lib/python3.6/dist-packages (from boto3->autogluon) (1.17.48)
Requirement already satisfied: jmespath<1.0.0,>=0.7.1 in /usr/local/lib/python3.6/dist-packages (from boto3->autogluon) (0.10.0)
Requirement already satisfied: s3transfer<0.4.0,>=0.3.0 in /usr/local/lib/python3.6/dist-packages (from boto3->autogluon) (0.3.3)
Requirement already satisfied: pynacl>=1.0.1 in /usr/local/lib/python3.6/dist-packages (from paramiko>=2.4->autogluon) (1.4.0)
Requirement already satisfied: bcrypt>=3.1.3 in /usr/local/lib/python3.6/dist-packages (from paramiko>=2.4->autogluon) (3.2.0)
Requirement already satisfied: xmltodict in /usr/local/lib/python3.6/dist-packages (from openml->autogluon) (0.12.0)
Requirement already satisfied: liac-arff>=2.4.0 in /usr/local/lib/python3.6/dist-packages (from openml->autogluon) (2.5.0)
Requirement already satisfied: packaging in /usr/local/lib/python3.6/dist-packages (from fastparquet==0.4.1->autogluon) (20.4)
Requirement already satisfied: numba>=0.28 in /usr/local/lib/python3.6/dist-packages (from fastparquet==0.4.1->autogluon) (0.48.0)
Requirement already satisfied: thrift>=0.11.0 in /usr/local/lib/python3.6/dist-packages (from fastparquet==0.4.1->autogluon) (0.13.0)
Requirement already satisfied: pluggy<0.8,>=0.5 in /usr/local/lib/python3.6/dist-packages (from pytest->autogluon) (0.7.1)
Requirement already satisfied: attrs>=17.4.0 in /usr/local/lib/python3.6/dist-packages (from pytest->autogluon) (20.1.0)
Requirement already satisfied: more-itertools>=4.0.0 in /usr/local/lib/python3.6/dist-packages (from pytest->autogluon) (8.4.0)
Requirement already satisfied: py>=1.5.0 in /usr/local/lib/python3.6/dist-packages (from pytest->autogluon) (1.9.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.6/dist-packages (from pytest->autogluon) (49.6.0)
Requirement already satisfied: atomicwrites>=1.0 in /usr/local/lib/python3.6/dist-packages (from pytest->autogluon) (1.4.0)
Requirement already satisfied: typing in /usr/local/lib/python3.6/dist-packages (from ConfigSpace<=0.4.10->autogluon) (3.7.4.3)
Requirement already satisfied: sortedcontainers!=2.0.0,!=2.0.1 in /usr/local/lib/python3.6/dist-packages (from distributed>=2.6.0->autogluon) (2.2.2)
Requirement already satisfied: toolz>=0.8.2 in /usr/local/lib/python3.6/dist-packages (from distributed>=2.6.0->autogluon) (0.10.0)
Requirement already satisfied: pyyaml in /usr/local/lib/python3.6/dist-packages (from distributed>=2.6.0->autogluon) (3.13)
Requirement already satisfied: zict>=0.1.3 in /usr/local/lib/python3.6/dist-packages (from distributed>=2.6.0->autogluon) (2.0.0)
Requirement already satisfied: tblib>=1.6.0 in /usr/local/lib/python3.6/dist-packages (from distributed>=2.6.0->autogluon) (1.7.0)
Requirement already satisfied: msgpack>=0.6.0 in /usr/local/lib/python3.6/dist-packages (from distributed>=2.6.0->autogluon) (1.0.0)
Requirement already satisfied: contextvars; python_version < "3.7" in /usr/local/lib/python3.6/dist-packages (from distributed>=2.6.0->autogluon) (2.4)
Requirement already satisfied: cloudpickle>=1.5.0 in /usr/local/lib/python3.6/dist-packages (from distributed>=2.6.0->autogluon) (1.6.0)
Requirement already satisfied: click>=6.6 in /usr/local/lib/python3.6/dist-packages (from distributed>=2.6.0->autogluon) (7.1.2)
Requirement already satisfied: protobuf in /usr/local/lib/python3.6/dist-packages (from autogluon-contrib-nlp->autogluon) (3.12.4)
Requirement already satisfied: regex in /usr/local/lib/python3.6/dist-packages (from autogluon-contrib-nlp->autogluon) (2019.12.20)
Requirement already satisfied: flake8 in /usr/local/lib/python3.6/dist-packages (from autogluon-contrib-nlp->autogluon) (3.8.3)
Requirement already satisfied: sentencepiece in /usr/local/lib/python3.6/dist-packages (from autogluon-contrib-nlp->autogluon) (0.1.91)
Requirement already satisfied: sacremoses>=0.0.38 in /usr/local/lib/python3.6/dist-packages (from autogluon-contrib-nlp->autogluon) (0.0.43)
Requirement already satisfied: tokenizers>=0.7.0 in /usr/local/lib/python3.6/dist-packages (from autogluon-contrib-nlp->autogluon) (0.8.1)
Requirement already satisfied: sacrebleu in /usr/local/lib/python3.6/dist-packages (from autogluon-contrib-nlp->autogluon) (1.4.13)
Requirement already satisfied: yacs>=0.1.6 in /usr/local/lib/python3.6/dist-packages (from autogluon-contrib-nlp->autogluon) (0.1.8)
Requirement already satisfied: joblib>=0.11 in /usr/local/lib/python3.6/dist-packages (from scikit-optimize->autogluon) (0.16.0)
Requirement already satisfied: pyaml>=16.9 in /usr/local/lib/python3.6/dist-packages (from scikit-optimize->autogluon) (20.4.0)
Requirement already satisfied: plotly in /usr/local/lib/python3.6/dist-packages (from catboost<0.24->autogluon) (4.4.1)
Requirement already satisfied: idna<3,>=2.5 in /usr/local/lib/python3.6/dist-packages (from requests->autogluon) (2.10)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /usr/local/lib/python3.6/dist-packages (from requests->autogluon) (1.24.3)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.6/dist-packages (from requests->autogluon) (2020.6.20)
Requirement already satisfied: chardet<4,>=3.0.2 in /usr/local/lib/python3.6/dist-packages (from requests->autogluon) (3.0.4)
Requirement already satisfied: cffi!=1.11.3,>=1.8 in /usr/local/lib/python3.6/dist-packages (from cryptography>=2.8->autogluon) (1.14.2)
Requirement already satisfied: docutils<0.16,>=0.10 in /usr/local/lib/python3.6/dist-packages (from botocore<1.18.0,>=1.17.48->boto3->autogluon) (0.15.2)
Requirement already satisfied: llvmlite<0.32.0,>=0.31.0dev0 in /usr/local/lib/python3.6/dist-packages (from numba>=0.28->fastparquet==0.4.1->autogluon) (0.31.0)
Requirement already satisfied: heapdict in /usr/local/lib/python3.6/dist-packages (from zict>=0.1.3->distributed>=2.6.0->autogluon) (1.0.1)
Requirement already satisfied: immutables>=0.9 in /usr/local/lib/python3.6/dist-packages (from contextvars; python_version < "3.7"->distributed>=2.6.0->autogluon) (0.14)
Requirement already satisfied: pyflakes<2.3.0,>=2.2.0 in /usr/local/lib/python3.6/dist-packages (from flake8->autogluon-contrib-nlp->autogluon) (2.2.0)
Requirement already satisfied: mccabe<0.7.0,>=0.6.0 in /usr/local/lib/python3.6/dist-packages (from flake8->autogluon-contrib-nlp->autogluon) (0.6.1)
Requirement already satisfied: pycodestyle<2.7.0,>=2.6.0a1 in /usr/local/lib/python3.6/dist-packages (from flake8->autogluon-contrib-nlp->autogluon) (2.6.0)
Requirement already satisfied: importlib-metadata; python_version < "3.8" in /usr/local/lib/python3.6/dist-packages (from flake8->autogluon-contrib-nlp->autogluon) (1.7.0)
Requirement already satisfied: retrying>=1.3.3 in /usr/local/lib/python3.6/dist-packages (from plotly->catboost<0.24->autogluon) (1.3.3)
Requirement already satisfied: pycparser in /usr/local/lib/python3.6/dist-packages (from cffi!=1.11.3,>=1.8->cryptography>=2.8->autogluon) (2.20)
Requirement already satisfied: zipp>=0.5 in /usr/local/lib/python3.6/dist-packages (from importlib-metadata; python_version < "3.8"->flake8->autogluon-contrib-nlp->autogluon) (3.1.0)

In [60]:
from autogluon import TabularPrediction as task
test_data = task.Dataset(file_path='hptest.csv')
train_data = task.Dataset(file_path="hptrain.csv")
predictor = task.fit(train_data=train_data, label='status')
y_pred = predictor.predict(test_data)

Loaded data from: hptest.csv | Columns = 24 / 24 | Rows = 231 -> 231
Loaded data from: hptrain.csv | Columns = 25 / 25 | Rows = 923 -> 923
No output_directory specified. Models will be saved in: AutogluonModels/ag-20200906_120922/
Beginning AutoGluon training ...
AutoGluon will save models to AutogluonModels/ag-20200906_120922/
AutoGluon Version:  0.0.13
Train Data Rows:    923
Train Data Columns: 25
Preprocessing data ...
Here are the 2 unique label values in your data:  ['acquired', 'closed']
AutoGluon infers your prediction problem is: binary  (because only two unique label-values observed).
If this is wrong, please specify `problem_type` argument in fit() instead (You may specify problem_type as one of: ['binary', 'multiclass', 'regression'])

Selected class <--> label mapping:  class 1 = closed, class 0 = acquired
Train Data Class Count: 2
Feature Generator processed 923 data points with 24 features
Original Features (raw dtypes):
	int64 features: 17
	float64 features: 7
Original Features (inferred dtypes):
	int features: 17
	float features: 7
Generated Features (special dtypes):
Processed Features (raw dtypes):
	int features: 17
	float features: 7
Processed Features:
	int features: 17
	float features: 7
	Data preprocessing and feature engineering runtime = 0.08s ...
AutoGluon will gauge predictive performance using evaluation metric: accuracy
To change this, specify the eval_metric argument of fit()
AutoGluon will early stop models using evaluation metric: accuracy
Fitting model: RandomForestClassifierGini ...
	0.8216	 = Validation accuracy score
	0.84s	 = Training runtime
	0.11s	 = Validation runtime
Fitting model: RandomForestClassifierEntr ...
	0.8108	 = Validation accuracy score
	1.03s	 = Training runtime
	0.11s	 = Validation runtime
Fitting model: ExtraTreesClassifierGini ...
	0.827	 = Validation accuracy score
	0.62s	 = Training runtime
	0.11s	 = Validation runtime
Fitting model: ExtraTreesClassifierEntr ...
	0.8324	 = Validation accuracy score
	0.62s	 = Training runtime
	0.11s	 = Validation runtime
Fitting model: KNeighborsClassifierUnif ...
	0.627	 = Validation accuracy score
	0.01s	 = Training runtime
	0.1s	 = Validation runtime
Fitting model: KNeighborsClassifierDist ...
	0.6162	 = Validation accuracy score
	0.0s	 = Training runtime
	0.11s	 = Validation runtime
Fitting model: LightGBMClassifier ...
	0.8216	 = Validation accuracy score
	0.46s	 = Training runtime
	0.01s	 = Validation runtime
Fitting model: CatboostClassifier ...
	0.827	 = Validation accuracy score
	0.94s	 = Training runtime
	0.01s	 = Validation runtime
Fitting model: NeuralNetClassifier ...
	0.773	 = Validation accuracy score
	4.19s	 = Training runtime
	0.02s	 = Validation runtime
Fitting model: LightGBMClassifierCustom ...
	0.8216	 = Validation accuracy score
	3.03s	 = Training runtime
	0.01s	 = Validation runtime
Fitting model: weighted_ensemble_k0_l1 ...
	0.8541	 = Validation accuracy score
	0.46s	 = Training runtime
	0.0s	 = Validation runtime
AutoGluon training complete, total runtime = 14.3s ...

In [61]:
# To create Dataframe of predicted value with particular respective index
res = pd.DataFrame(y_pred) #preditcions are nothing but the final predictions of your model on input features of your new unseen test data
res.index = td.index # its important for comparison. Here "test_new" is your new test dataset
res.columns = ["prediction"]

# To download the csv file locally
from google.colab import files
res.to_csv('hpi.csv')         
files.download('hpi.csv')